//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_LucyCaceres
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SqlDatabaseEntities : DbContext
    {
        public SqlDatabaseEntities()
            : base("name=SqlDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ciudadanos> Ciudadanos { get; set; }
        public virtual DbSet<MediosTransporte> MediosTransporte { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<TipoDocumentos> TipoDocumentos { get; set; }
        public virtual DbSet<TipoDocumentosxCiudadano> TipoDocumentosxCiudadano { get; set; }
        public virtual DbSet<TransportexCiudadano> TransportexCiudadano { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
